# Generated by Django 2.0.5 on 2018-05-18 14:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_uuid', models.UUIDField(default=uuid.UUID('42550e74-5aa8-11e8-b81e-acbc32900877'))),
                ('device_name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_code', models.CharField(max_length=200)),
                ('type_name', models.CharField(max_length=500)),
                ('type_desc', models.TextField()),
            ],
            options={
                'db_table': 'device_type',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='device_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceType'),
        ),
    ]
