# Generated by Django 2.0.5 on 2018-05-18 14:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_uuid',
            field=models.UUIDField(default=uuid.UUID('a36116e8-5aa8-11e8-8fad-acbc32900877')),
        ),
    ]
