# Generated by Django 2.0.5 on 2018-05-18 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20180518_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_uuid',
            field=models.UUIDField(default=uuid.UUID('e220d268-5aaf-11e8-8d94-acbc32900877')),
        ),
    ]
